import '../css/style.css';
import img1 from '../img/sneakers1.jpg';
import img2 from '../img/sneakers2.jpg';
import img3 from '../img/sneakers3.jpg';
import sneaker from '../img/sneaker.svg';
import other from '../img/other-clothes.svg';
import triangle from '../img/triangle.svg';
import x from '../img/x.svg';
import '../js/functions/nouislider.js';
import '../js/functions/rangeSlider.js';
import '../js/functions/windowWidth.js';